/**
 * @file tuya_config.h
 * @brief IoT specific configuration file
 */

#ifndef TUYA_CONFIG_H_
#define TUYA_CONFIG_H_

#include "tuya_cloud_types.h"

/**
 * @brief configure the product information
 *
 * TUYA_PRODUCT_ID: PID, create on the Tuya IoT platform
 * TUYA_DEVICE_UUID: UUID, the unique ID of the device, you can get 2 free from Tuya IoT platform
 * TUYA_DEVICE_AUTHKEY: AUTHKEY, the private key of the device, you can get 2 free from Tuya IoT platform
 *
 * detail please refer to: https://developer.tuya.com/cn/docs/iot-device-dev/application-creation?id=Kbxw7ket3aujc
 *
 * warning: please replace these production information with your product id and license, otherwise the demo cannot
 * work.
 *
 */

#ifndef TUYA_PRODUCT_ID
#define TUYA_PRODUCT_ID "p320pepzvmm1ghse"
#endif

/*
 * The license is a credential: never hardcode it here, this file is tracked by git.
 * Set CONFIG_TUYA_OPENSDK_UUID / CONFIG_TUYA_OPENSDK_AUTHKEY in the gitignored
 * app_default.config (or config/TUYA_T5AI_CORE.config), or flash the license with
 * `tos.py auth` and leave both empty.
 */
#ifndef TUYA_OPENSDK_UUID
#define TUYA_OPENSDK_UUID ""
#endif
#ifndef TUYA_OPENSDK_AUTHKEY
#define TUYA_OPENSDK_AUTHKEY ""
#endif

/**
 * @brief PINCODE for AP provisioning
 *
 * TUYA_NETCFG_PINCODE: a random PINCODE for AP provisioning, PINCODE was generated BY TUYA PMS system!!!
 *
 * WARNING: PINCODE is mandatory for AP provisioning
 */
// #define TUYA_NETCFG_PINCODE   "69832860"

#endif
